name: Test-Linux-mbedTLS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd matter; cargo build --verbose --no-default-features --features crypto_mbedtls
    - name: Run tests
      run: cd matter; cargo test --verbose --no-default-features --features crypto_mbedtls -- --test-threads=1
